# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dafeb52bde9d66e42832fd51660d52f2d9a29abd3d9c52acf600d4af618fd4b980202e39420aa40649af8abe982189b50e967cec0912ba2566231204e25d09e9

test:
  secret_key_base: 8a74d08230313dbd613179d586c4379284140a30eedd86479f2b418d8cf2b85eafa03040eb9bc9c2fabb5bae1d3305fa954a465d34235c3fa74a285236e60b2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
